package Nagusia;

// Generated 9 ene. 2020 8:50:41 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Ostatu generated by hbm2java
 */

@Entity
@Table(name = "ostatu")
public class Ostatu implements java.io.Serializable {
	
	@Id
	@Column(name="id_Ostatu")
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Integer id_Ostatu;
	@Column
	private String Izena;
	@Column
	private String Deskribapena;
	@Column
	private String Ostatu_Mota;
	@Column
	private int Logela_Kop;
	@Column
	private String Kokapena;
	@Column
	private String Telefonoa;
	@Column
	private String Email;
	@Column
	private String Latitudea;
	@Column
	private String Longitudea;

	public Ostatu() {
	}

	public Ostatu(String izena, String deskribapena, String ostatuMota, int logelaKop, String kokapena,
			String telefonoa, String email, String latitudea, String longitudea) {
		this.Izena = izena;
		this.Deskribapena = deskribapena;
		this.Ostatu_Mota = ostatuMota;
		this.Logela_Kop = logelaKop;
		this.Kokapena = kokapena;
		this.Telefonoa = telefonoa;
		this.Email = email;
		this.Latitudea = latitudea;
		this.Longitudea = longitudea;
	}
	
	public Ostatu(String izena, String deskribapena, String ostatuMota, String kokapena,
			String telefonoa, String email, String latitudea, String longitudea) {
		this.Izena = izena;
		this.Deskribapena = deskribapena;
		this.Ostatu_Mota = ostatuMota;
		this.Kokapena = kokapena;
		this.Telefonoa = telefonoa;
		this.Email = email;
		this.Latitudea = latitudea;
		this.Longitudea = longitudea;
	}
	
	public Integer getIdOstatu() {
		return this.id_Ostatu;
	}

	public void setIdOstatu(Integer idOstatu) {
		this.id_Ostatu = idOstatu;
	}

	public String getIzena() {
		return this.Izena;
	}

	public void setIzena(String izena) {
		this.Izena = izena;
	}

	public String getDeskribapena() {
		return this.Deskribapena;
	}

	public void setDeskribapena(String deskribapena) {
		this.Deskribapena = deskribapena;
	}

	public String getOstatuMota() {
		return this.Ostatu_Mota;
	}

	public void setOstatuMota(String ostatuMota) {
		this.Ostatu_Mota = ostatuMota;
	}

	public int getLogelaKop() {
		return this.Logela_Kop;
	}

	public void setLogelaKop(int logelaKop) {
		this.Logela_Kop = logelaKop;
	}

	public String getKokapena() {
		return this.Kokapena;
	}

	public void setKokapena(String kokapena) {
		this.Kokapena = kokapena;
	}

	public String getTelefonoa() {
		return this.Telefonoa;
	}

	public void setTelefonoa(String telefonoa) {
		this.Telefonoa = telefonoa;
	}

	public String getEmail() {
		return this.Email;
	}

	public void setEmail(String email) {
		this.Email = email;
	}

	public String getLatitudea() {
		return this.Latitudea;
	}

	public void setLatitudea(String latitudea) {
		this.Latitudea = latitudea;
	}

	public String getLongitudea() {
		return this.Longitudea;
	}

	public void setLongitudea(String longitudea) {
		this.Longitudea = longitudea;
	}

}
